# Generated by Django 5.1.2 on 2024-10-20 02:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['pub_date'], name='polls_quest_pub_dat_5d0c19_idx'),
        ),
    ]
