# Generated by Django 5.1.2 on 2024-10-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.URLField(default='https://placeholder-link.com'),
            preserve_default=False,
        ),
    ]
